name: github-action
run-name: ${{ github.actor }} is out building GitHub Actions

on:
  push:
    # Pattern matched against refs/tags
    tags:        
      - '**' 

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build Maven Projects
        run: |
          mvn clean package -f ./application/pom.xml
          mvn clean package -f ./process1/pom.xml
          mvn clean package -f ./process2/pom.xml
          mvn clean package -f ./compensation/pom.xml
          mvn clean package -f ./analysis1/pom.xml
          mvn clean package -f ./analysis2/pom.xml
          mvn clean package -f ./supporting/pom.xml

      - name: Docker Build and push for Application
        uses: docker/build-push-action@v4
        with:
          context: ./application
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/application:latest
            ghcr.io/${{ github.repository }}/application:${{ github.ref_name }}
            
      - name: Docker Build and push for Process1
        uses: docker/build-push-action@v4
        with:
          context: ./process1
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/process1:latest
            ghcr.io/${{ github.repository }}/process1:${{ github.ref_name }}
            
      - name: Docker Build and push for Process2
        uses: docker/build-push-action@v4
        with:
          context: ./process2
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/process2:latest
            ghcr.io/${{ github.repository }}/process2:${{ github.ref_name }}
            
      - name: Docker Build and push for Compensation
        uses: docker/build-push-action@v4
        with:
          context: ./compensation
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/compensation:latest
            ghcr.io/${{ github.repository }}/compensation:${{ github.ref_name }}
            
      - name: Docker Build and push for Analysis1
        uses: docker/build-push-action@v4
        with:
          context: ./analysis1
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/analysis1:latest
            ghcr.io/${{ github.repository }}/analysis1:${{ github.ref_name }}
            
      - name: Docker Build and push for Analysis2
        uses: docker/build-push-action@v4
        with:
          context: ./analysis2
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/analysis2:latest
            ghcr.io/${{ github.repository }}/analysis2:${{ github.ref_name }}
            
      - name: Docker Build and push for Supporting
        uses: docker/build-push-action@v4
        with:
          context: ./supporting
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/supporting:latest
            ghcr.io/${{ github.repository }}/supporting:${{ github.ref_name }}
            
