---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: application
  labels:
    app: application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: application
  template:
    metadata:
      labels:
        app: application
    spec:
      containers:
        - name: application
          image: username/application:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: process1
  labels:
    app: process1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: process1
  template:
    metadata:
      labels:
        app: process1
    spec:
      containers:
        - name: process1
          image: username/process1:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: process2
  labels:
    app: process2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: process2
  template:
    metadata:
      labels:
        app: process2
    spec:
      containers:
        - name: process2
          image: username/process2:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: compensation
  labels:
    app: compensation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: compensation
  template:
    metadata:
      labels:
        app: compensation
    spec:
      containers:
        - name: compensation
          image: username/compensation:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: analysis1
  labels:
    app: analysis1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: analysis1
  template:
    metadata:
      labels:
        app: analysis1
    spec:
      containers:
        - name: analysis1
          image: username/analysis1:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: analysis2
  labels:
    app: analysis2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: analysis2
  template:
    metadata:
      labels:
        app: analysis2
    spec:
      containers:
        - name: analysis2
          image: username/analysis2:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: supporting
  labels:
    app: supporting
spec:
  replicas: 1
  selector:
    matchLabels:
      app: supporting
  template:
    metadata:
      labels:
        app: supporting
    spec:
      containers:
        - name: supporting
          image: username/supporting:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5


---


apiVersion: v1
kind: Service
metadata:
  name: application
  labels:
    app: application
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: application


---


apiVersion: v1
kind: Service
metadata:
  name: process1
  labels:
    app: process1
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: process1


---


apiVersion: v1
kind: Service
metadata:
  name: process2
  labels:
    app: process2
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: process2


---


apiVersion: v1
kind: Service
metadata:
  name: compensation
  labels:
    app: compensation
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: compensation


---


apiVersion: v1
kind: Service
metadata:
  name: analysis1
  labels:
    app: analysis1
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: analysis1


---


apiVersion: v1
kind: Service
metadata:
  name: analysis2
  labels:
    app: analysis2
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: analysis2


---


apiVersion: v1
kind: Service
metadata:
  name: supporting
  labels:
    app: supporting
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: supporting

