openapi: 3.0.2
info:
  title: Analysis2
  version: 0.0.1
  description: API definition of analysis2
  contact:
    name: creator's name
    url: http://creator.homepage.address
    email: creator@creator.com
  license:
    name: MIT License
    url: https://opensource.org/licenses/MIT
paths:
  /analysis2s:
    summary: Global operations on analysis2s
    get:
      tags:
      - analysis2s
      responses:
        "200":
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Analysis2'
              examples:
                analysis2s_json:
                  value:
                  -
                    id: 1
          description: Get list of analysis2s
      operationId: GetAnalysis2
      summary: Get list of analysis2s
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Analysis2'
            examples:
              1:
                value:
                  id: 1
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Analysis2'
              examples:
                1:
                  value:
                    id: 1
          description: Changed Analysis2
      operationId: Post Analysis2
      summary: Post Analysis2        
  /analysis2s/{id}:
    summary: Specific operation on analysis2s
    get:
      parameters:
      - examples:
          1:
            value: 1
        name: id
        description: Analysis2 name
        schema:
          type: integer
        in: path
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Analysis2'
              examples:
                1:
                  value:
                    id: 1
          description: analysis2s with specified id
      operationId: GetAnalysis2ById
      summary: Get Analysis2 by id
      description: Get Analysis2 by id
    patch:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Analysis2'
            examples:
              1:
                value:
                  id: 1
        required: true
      parameters:
      - examples:
          1:
            value: 1
        name: id
        description: Analysis2 name
        schema:
          type: integer
        in: path
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Analysis2'
              examples:
                1:
                  value:
                    id: 1
          description: Changed Analysis2
      operationId: PatchAnalysis2
      summary: Patch existing Analysis2
    parameters:
    - name: id
      description: Analysis2 id
      schema:
        type: integer
      in: path
      required: true
components:
  schemas:
    Analysis2:
      title: Root Type for Analysis2
      description: The root of the Analysis2 type's schema.
      type: object
      properties:
        id:
          description: id of this Analysis2
          type: integer
tags:
  - name: Analysis2
    description: Analysis2 resource
